// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxSDHPY3PL6uD_nQPNmxyEXSSFQLgiaok',
    appId: '1:932425915689:web:33c28be5e33a9f2d5ceb38',
    messagingSenderId: '932425915689',
    projectId: 'referee-application',
    authDomain: 'referee-application.firebaseapp.com',
    storageBucket: 'referee-application.firebasestorage.app',
    measurementId: 'G-XPSEMRK4KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq2FzdCkOdhVIHOltBPYxu6w_dg5A5SOQ',
    appId: '1:932425915689:android:2c16269315dcca3d5ceb38',
    messagingSenderId: '932425915689',
    projectId: 'referee-application',
    storageBucket: 'referee-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvsmhvjcjabUfFvPgjUlj8-6vQn3BmPls',
    appId: '1:932425915689:ios:4f639ba4626065c75ceb38',
    messagingSenderId: '932425915689',
    projectId: 'referee-application',
    storageBucket: 'referee-application.firebasestorage.app',
    iosBundleId: 'com.example.refereeAplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvsmhvjcjabUfFvPgjUlj8-6vQn3BmPls',
    appId: '1:932425915689:ios:4f639ba4626065c75ceb38',
    messagingSenderId: '932425915689',
    projectId: 'referee-application',
    storageBucket: 'referee-application.firebasestorage.app',
    iosBundleId: 'com.example.refereeAplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxSDHPY3PL6uD_nQPNmxyEXSSFQLgiaok',
    appId: '1:932425915689:web:04a3b62ef0b070c55ceb38',
    messagingSenderId: '932425915689',
    projectId: 'referee-application',
    authDomain: 'referee-application.firebaseapp.com',
    storageBucket: 'referee-application.firebasestorage.app',
    measurementId: 'G-7G0EFHH6X7',
  );
}
